<?php $data = ffWPPost::__set_state(array(
   'ID' => '26',
   'post_author' => '1',
   'post_date' => '2013-08-08 14:02:43',
   'post_date_gmt' => '2013-08-08 14:02:43',
   'post_content' => 'Passepartout went timidly ashore on this so curious territory of the Sons of the Sun. He had nothing better to do than, taking chance for his guide, to wander aimlessly through the streets of Yokohama. He found himself at first in a thoroughly European quarter, the houses having low fronts, and being adorned with verandas, beneath which he caught glimpses of neat peristyles. This quarter occupied, with its streets, squares, docks, and warehouses, all the space between the "promontory of the Treaty" and the river.

Here, as at Hong Kong and Calcutta, were mixed crowds of all races, Americans and English, Chinamen and Dutchmen, mostly merchants ready to buy or sell anything. The Frenchman felt himself as much alone among them as if he had dropped down in the midst of Hottentots. He had, at least, one resource to call on the French and English consuls at Yokohama for assistance.',
   'post_title' => 'It is situated in the bay of Yeddo, <br/>and at but a short distance from',
   'post_excerpt' => '',
   'post_status' => 'publish',
   'comment_status' => 'open',
   'ping_status' => 'open',
   'post_password' => '',
   'post_name' => 'about-us',
   'to_ping' => '',
   'pinged' => '',
   'post_content_filtered' => '',
   'post_modified' => '2013-08-14 12:13:28',
   'post_modified_gmt' => '2013-08-14 12:13:28',
   'post_parent' => '0',
   'guid' => 'http://demo.freshface.net/file/cn/wp/?page_id=26',
   'menu_order' => '0',
   'post_type' => 'page',
   'post_mime_type' => '',
   'comment_count' => '0',
   'post_meta' => 
  array (
    'wprequestbutton---button_url' => '#',
    '_edit_last' => '1',
    'wpclients---items---5---url' => '',
    'wprequestbutton---enablesection' => '1',
    'wprequestbutton---button_title' => 'Request a quote',
    'wpclients---items---5---image' => 'http://demo.freshface.net/file/cn/wp/wp-content/uploads/2013/08/ofico_normal.jpg',
    'wpclients---items---4---url' => '',
    'wpclients---enablesection' => '1',
    'wpclients---section_title' => 'Clients',
    'wpclients---items---1---image' => 'http://demo.freshface.net/file/cn/wp/wp-content/uploads/2013/08/bravel_normal.jpg',
    'wpclients---items---1---url' => '',
    'wpclients---items---2---image' => 'http://demo.freshface.net/file/cn/wp/wp-content/uploads/2013/08/hitekt_normal.jpg',
    'wpclients---items---2---url' => '',
    'wpclients---items---3---image' => 'http://demo.freshface.net/file/cn/wp/wp-content/uploads/2013/08/impulst_normal.jpg',
    'wpclients---items---3---url' => '',
    'wpclients---items---4---image' => 'http://demo.freshface.net/file/cn/wp/wp-content/uploads/2013/08/locity_normal.jpg',
    'wpteam---items---3---text' => 'Account Support',
    'wpimagestripe---enablesection' => '1',
    'wpimagestripe---image_source' => 'http://demo.freshface.net/file/cn/wp/wp-content/uploads/2013/08/office.jpg',
    'wpteam---items---3---image' => 'http://demo.freshface.net/file/cn/wp/wp-content/uploads/2013/08/031.jpg',
    'wpteam---items---3---title' => 'Jill Doe',
    'wpteam---items---2---title' => 'John Doe',
    'wpteam---items---2---text' => 'Founder, Managing Director',
    '_edit_lock' => '1376483388:1',
    '_wp_page_template' => 'page-about.php',
    'wpteam---items---1---text' => 'CEO',
    'wpteam---items---2---image' => 'http://demo.freshface.net/file/cn/wp/wp-content/uploads/2013/08/021.jpg',
    'wpcontentsectiontitle---section_title' => 'History',
    'wphighlight---enablesection' => '1',
    'wphighlight---highlight_title' => 'Passepartout went timidly ashore on this so',
    'wphighlight---highlight_content' => 'Passepartout went timidly ashore on this so curious territory of the Sons of the Sun. He had nothing better to do than, taking chance for his guide, to wander aimlessly through the streets of Yokohama. He found himself at first in a thoroughly European quarter, the houses having low fronts, and being adorned with verandas, beneath which he caught glimpses of neat peristyles. This quarter occupied, with its streets',
    'wpteam---enablesection' => '1',
    'wpteam---items---1---title' => 'Jane Doe',
    'wpteam---section_title' => 'Team',
    'wpteam---items---1---image' => 'http://demo.freshface.net/file/cn/wp/wp-content/uploads/2013/08/011.jpg',
    'wppreface---description' => 'Who we are, what we do and how we do it',
    'wppreface---show' => '1',
    'wppreface---title' => 'About us',
    'wpgmap---isenabled' => '0',
    'wpgmap---latitude' => '',
    'wpgmap---longtitude' => '',
    'wpgmap---zoom' => '16',
    'wpadditionalcontactinfo---social_title' => 'Social',
    'wpadditionalcontactinfo---social_content' => '',
    'wpadditionalcontactinfo---enablesocial' => '0',
    'wpadditionalcontactinfo---enablecontactphone' => '0',
    'wpadditionalcontactinfo---contact_content' => 'Tel: 0680 710 13 36 
Fax: 0680 710 13 99',
    'wpadditionalcontactinfo---contact_email_title' => 'DROP US AN EMAIL',
    'wpadditionalcontactinfo---contact_email_email' => 'your@email.com',
    'wpadditionalcontactinfo---enablecontact' => '0',
    'wpadditionalcontactinfo---contact_title' => 'Contact',
    'wpadditionalcontactinfo---enablecontactemail' => '0',
    'wpadditionalcontactinfo---address_content' => 'Bognergasse 16 
9131 Wien 
Austria',
    'wpadditionalcontactinfo---enableaddress' => '0',
    'wpadditionalcontactinfo---address_title' => 'Address',
    'wppagesettings---comments-show' => '0',
    'wppagesettings---sidebar-show' => '0',
  ),
   'connected_taxonomies' => 
  array (
  ),
));