<?php $data = ffWPPost::__set_state(array(
   'ID' => '51',
   'post_author' => '1',
   'post_date' => '2013-08-12 09:58:28',
   'post_date_gmt' => '2013-08-12 09:58:28',
   'post_content' => '',
   'post_title' => 'Blog',
   'post_excerpt' => '',
   'post_status' => 'publish',
   'comment_status' => 'open',
   'ping_status' => 'open',
   'post_password' => '',
   'post_name' => 'blog',
   'to_ping' => '',
   'pinged' => '',
   'post_content_filtered' => '',
   'post_modified' => '2013-08-12 10:44:53',
   'post_modified_gmt' => '2013-08-12 10:44:53',
   'post_parent' => '0',
   'guid' => 'http://demo.freshface.net/file/cn/wp/?p=51',
   'menu_order' => '5',
   'post_type' => 'nav_menu_item',
   'post_mime_type' => '',
   'comment_count' => '0',
   'post_meta' => 
  array (
    '_menu_item_type' => 'taxonomy',
    '_menu_item_menu_item_parent' => '0',
    '_menu_item_object_id' => '8',
    '_menu_item_object' => 'category',
    '_menu_item_target' => '',
    '_menu_item_classes' => 'a:1:{i:0;s:0:"";}',
    '_menu_item_xfn' => '',
    '_menu_item_url' => '',
  ),
   'connected_taxonomies' => 
  array (
    0 => 
    array (
      'term_id' => '3',
      'term_taxonomy_id' => '3',
      'taxonomy' => 'nav_menu',
    ),
  ),
));